NumPy Arrays

In [61]:
import numpy as np


In [5]:
my_list=[1,2,3,4,5]
ar=np.array(my_list)
ar

array([1, 2, 3, 4, 5])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
mat=np.array(my_mat)
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [16]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,5,100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(5)

array([0.08428624, 0.43410524, 0.47618478, 0.06834685, 0.32489576])

In [24]:
np.random.rand(5,5)

array([[0.69784965, 0.96032952, 0.63139681, 0.07865832, 0.44493061],
       [0.03204308, 0.02082717, 0.06025458, 0.9071907 , 0.10960827],
       [0.70668401, 0.76855463, 0.94192034, 0.3557795 , 0.16818972],
       [0.91860849, 0.31320283, 0.93585028, 0.98620171, 0.19876634],
       [0.49383785, 0.73676041, 0.45225441, 0.94377353, 0.40413413]])

In [26]:
np.random.randn(2,2)

array([[-0.27767375,  0.44555777],
       [-1.03202155, -1.85255583]])

In [33]:
np.random.randint(1,100,10)

array([60, 84,  4, 10, 53, 95, 74, 82, 35, 94])

In [35]:
arr=np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
ranarr=np.random.randint(0,50,10)
ranarr

array([21, 28, 28,  7, 46, 29, 41, 37, 12,  3])

In [39]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
ranarr.max()

46

In [46]:
ranarr.min()

3

In [47]:
ranarr

array([21, 28, 28,  7, 46, 29, 41, 37, 12,  3])

In [48]:
ranarr.argmax()

4

In [50]:
ranarr.argmin()

9

In [53]:
arr.shape

(25,)

In [54]:
arr=arr.reshape(5,5)

In [56]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
arr.shape


(5, 5)

In [60]:
arr.dtype

dtype('int32')

In [62]:
from numpy.random import randint

In [63]:
randint(2,10)

7