In [3]:
import numpy as np

In [4]:
arr=np.arange(0,11)

In [5]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr[6:]

array([ 6,  7,  8,  9, 10])

In [12]:
slice_of_arr=arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [16]:
arr_copy=arr.copy()

In [17]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy[:]=100


In [20]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [23]:
arr_2d=np.array([[1,2,3],[40,90,80],[77,88,66]])
arr_2d

array([[ 1,  2,  3],
       [40, 90, 80],
       [77, 88, 66]])

In [26]:
arr_2d[0]

array([1, 2, 3])

In [28]:
arr_2d[:2,1:]

array([[ 2,  3],
       [90, 80]])

In [35]:
arr_2d=np.arange(60).reshape(6,10)
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])